In [9]:
import numpy as np
import random



1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [21]:
array = np.random.randint(10,99,50)
array[::5]

array([60, 71, 31, 58, 40, 34, 72, 88, 44, 48])


2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [26]:
array1 = np.random.randint(0,21,30)
array1[1::2]

array([10,  1,  9,  2,  0,  6,  6, 13, 14,  3, 20,  6,  1,  1, 17])

3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [38]:
array2 = np.round(np.random.uniform(0,3,(4, 6)), 2)
array2

array([[1.98, 0.1 , 1.81, 1.91, 0.57, 0.96],
       [2.49, 1.64, 1.34, 0.9 , 1.87, 1.83],
       [2.43, 1.41, 1.96, 0.18, 2.2 , 1.95],
       [1.51, 2.09, 1.73, 0.86, 2.2 , 1.53]])

In [52]:
array2_1= np.round(np.random.rand(4,6),2)
array2_1

array([[0.62, 0.65, 0.  , 0.63, 0.7 , 0.05],
       [0.56, 0.69, 0.93, 0.38, 0.52, 0.09],
       [0.88, 0.74, 0.71, 0.61, 0.48, 0.94],
       [0.4 , 0.76, 0.57, 0.48, 0.41, 0.01]])

In [ ]:
array2_2= np.random.randint(1,99,(4,6))


array([[28, 25, 72, 49, 14,  8],
       [61, 72, 90, 79, 91, 65],
       [84, 93, 93, 88, 81, 52],
       [75, 71, 21, 52, 65, 51]])

In [54]:
array2_3=array2_1+array2_2
array2_3

array([[28.62, 25.65, 72.  , 49.63, 14.7 ,  8.05],
       [61.56, 72.69, 90.93, 79.38, 91.52, 65.09],
       [84.88, 93.74, 93.71, 88.61, 81.48, 52.94],
       [75.4 , 71.76, 21.57, 52.48, 65.41, 51.01]])

In [55]:
np.round(2.556298,2)

2.56


BONUS: Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [48]:

array3 = np.random.randint(0,101,(2,4,6))
array3

array([[[15, 38,  0, 66, 30, 70],
        [43, 45, 31, 68, 42, 32],
        [51, 48, 94, 29, 86, 60],
        [79, 54, 28, 78, 76, 13]],

       [[50, 39, 25, 61,  8, 15],
        [25, 14, 97, 72, 99, 93],
        [93, 25, 81, 94, 59, 52],
        [26, 62, 12, 67,  6, 78]]])

Reshape y Transpose:


1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [63]:
array_4 = np.random.randint(0,101,(2,3,4))
array_4_2 = np.reshape(array_4,(2,12))
array_4_2

array([[54, 36, 96, 44, 70, 17, 97, 30, 32, 76, 60, 66],
       [99, 19, 27, 30,  3, 96, 90,  4, 91, 36, 14, 66]])

2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [66]:
array_5 = np.random.randint(2,61,(3,4,5))
array_5_2 = np.reshape(array_5,(3,20))
array_5_2

array([[56, 22,  5,  5, 59, 21, 43,  8, 42, 28, 33, 46, 46,  9, 56, 46,
        37, 23, 57, 40],
       [52, 20, 16, 46,  8, 60, 44, 52, 32, 31, 11, 18, 46, 23, 60, 48,
        42, 44, 57, 28],
       [18, 60, 23, 39,  5,  8, 40, 38,  6, 39, 32,  8, 31,  8, 53, 43,
        58, 21, 21, 56]])


3. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [67]:
array_6 = np.random.randint(2,61,(3,4,5))
array_6_2 = np.transpose(array_5,(3,20))
array_6_2

ValueError: axes don't match array